### PR TITLE
Add off, on tasks.

### PR DESCRIPTION
**Pull request by tobias**

### CODE REVIEW

**Comment by gfredericks** [comment]
omg

**Comment by tobias** [comment]
Anything I can do to help this get merged? It's been sitting for over 2 hours, and is currently tripping us up in production.

**Comment by gfredericks** [comment]
I'm not sure I like the mutable state idea. I was imagining a higher-order-task, like

`lein without-lein-lein echo foo # blows up saying echo is not a known task`

**Comment by gfredericks** [comment]
in particular `lein do without-lein-lein test, echo done` would run without error

**Comment by tobias** [comment]
Man, I feel _really_ sorry for wasting both our times on this. We are
now closer to death than we were when this conversation started, and
what do we have to show for it? Nothing.

Moments fall like sand through our fingers, all we can do is try to
hold on to them, but it's an impossible task. All things fade.

When I was a child, I suppose I was like most - I wondered what my
future would be like. I didn't imagine doing great or important
things, I didn't have enough understanding of the world to do so. I
imagined future me doing the same things child me did - playing
games. It's amazing how right I was - that future has come. But, with
adulthood, I have raised my eyes from the ground, and realize my own
mortality.

What is a game, anyway? Isn't it a way to occupy the mind as time
slips away? If so, then isn't the work we spend most of our time on a
game?

We are all Ozymandias.

**Pull request closed without merging**
